openapi: "3.0.3"
info: 
  version: "1.0.0"
  title: "Study"
  description: "메인 기능 api입니다."
servers:
  - url: http://localhost:3000/
paths:
  $ref: './paths/_index.yaml'
components:
  $ref: './components/_index.yaml'